global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    environment: test

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["docker-prometheus:9090"]

remote_write:
- url: 'http://docker-prometheus:9090/api/v1/write'