// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: shoppaymentApi.proto

package go_micro_api_shop_paymentApi

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for ShopPaymentApi service

func NewShopPaymentApiEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for ShopPaymentApi service

type ShopPaymentApiService interface {
	//直接退款功能
	PayPalRefund(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type shopPaymentApiService struct {
	c    client.Client
	name string
}

func NewShopPaymentApiService(name string, c client.Client) ShopPaymentApiService {
	return &shopPaymentApiService{
		c:    c,
		name: name,
	}
}

func (c *shopPaymentApiService) PayPalRefund(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "ShopPaymentApi.PayPalRefund", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ShopPaymentApi service

type ShopPaymentApiHandler interface {
	//直接退款功能
	PayPalRefund(context.Context, *Request, *Response) error
}

func RegisterShopPaymentApiHandler(s server.Server, hdlr ShopPaymentApiHandler, opts ...server.HandlerOption) error {
	type shopPaymentApi interface {
		PayPalRefund(ctx context.Context, in *Request, out *Response) error
	}
	type ShopPaymentApi struct {
		shopPaymentApi
	}
	h := &shopPaymentApiHandler{hdlr}
	return s.Handle(s.NewHandler(&ShopPaymentApi{h}, opts...))
}

type shopPaymentApiHandler struct {
	ShopPaymentApiHandler
}

func (h *shopPaymentApiHandler) PayPalRefund(ctx context.Context, in *Request, out *Response) error {
	return h.ShopPaymentApiHandler.PayPalRefund(ctx, in, out)
}
